const menu = [
    {
      id: 1,
      title: "Burger and fries",
      category: "Burgers",
      price: 15.99,
      img: require('./assets/imgs/burgers/burger1.jpg'),
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: "Chacoal Burger",
      category: "Burgers",
      price: 13.99,
      img: require('./assets/imgs/burgers/burger2.jpg'),
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: "Healthy toast",
      category: "Toasts",
      price: 6.99,
      img: require('./assets/imgs/toasts/toast1.jpg'),
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: "Boneless Chicken",
      category: "Fries",
      price: 20.99,
      img: require('./assets/imgs/chickens/chicken1.jpg'),
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: "Cheese Burger",
      category: "Burgers",
      price: 22.99,
      img: require('./assets/imgs/burgers/burger3.jpg'),
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: "Spicy Chicken",
      category: "Fries",
      price: 18.99,
      img: require('./assets/imgs/chickens/chicken3.jpg'),
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: "Popular Fries Set",
      category: "Fries",
      price: 22.99,
      img: require('./assets/imgs/chickens/chicken4.jpg'),
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: "Egg Sandwich Toast",
      category: "Toasts",
      price: 12.99,
      img: require('./assets/imgs/toasts/toast2.png'),
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: "Ham Toast",
      category: "Toasts",
      price: 12.99,
      img: require('./assets/imgs/toasts/toast3.jpg'),
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: "Loaded Chicken",
      category: "Fries",
      price: 39.99,
      img: require('./assets/imgs/chickens/chicken5.jpg'),
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 11,
      title: "Chewy Burger",
      category: "Burgers",
      price: 19.99,
      img: require('./assets/imgs/burgers/burger4.jpg'),
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 12,
      title: "Stack Meat Burger",
      category: "Burgers",
      price: 19.99,
      img: require('./assets/imgs/burgers/burger5.jpg'),
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 13,
      title: "Coca Cola",
      category: "Drinks",
      price: 5,
      img: require('./assets/imgs/drinks/CocaCola.jpg'),
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 14,
      title: "Pepsi",
      category: "Drinks",
      price: 5,
      img: require('./assets/imgs/drinks/Pepsi.jpg'),
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 15,
      title: "Coca Cola",
      category: "Drinks",
      price: 5,
      img: require('./assets/imgs/drinks/7Up.jpg'),
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];


  export default menu;